spacing         = 1
padding         = 0
hide_ascii      = false
# prefer_small_ascii = true
separator       = "-" 
key_color       = "#Fccf6C"
separator_color = "#71f094"

[custom_ascii]
color           = "#ff5370"
path            = "~/.config/macchina/ascii/tux"

[palette]
type            = "Light"
glyph           = " î‚¶î‚´"
visible         = true

[bar]
glyph           = "ß‹"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = false

[box]
# title           = " Safdar Awan "
border          = "rounded"
visible         = true

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false
pool            = "base"

[keys]
de              = "DE"
resolution      = "Resolution"
distro          = " ïŒƒ "
kernel          = " îœ’ "
shell           = " $ "
packages        = " ï£• "
host            = " ðŸ§‘ "
battery         = "Battery"
os              = " ï ¡ "
wm              = " ïª±"
terminal        = " ï’‰ "
memory          = " î®‰ "
machine         = " ï¡¸ "
local_ip        = "Local IP"
backlight       = "Brightness"
cpu             = " ï¡š "
cpu_load        = "CPU Load"
uptime          = " ï¨™"
