# format = """
# $directory$git_branch
# $character
# """

# Timeout for starship to scan files (in milliseconds).
scan_timeout = 1000

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 700

# Disable the blank line at the start of the prompt
add_newline = false

# TODO: figure out how to create a function that will create a new line 
# for the character only when there are three or more components are visible 
# on the terminal

# format = """
# $directory$git_branch$git_commit$git_state$git_status$package$lua$nodejs$python$character
# """

[directory]
truncation_length = 1
read_only = " ï ½"
# truncation_symbol = "â€¦/"
format = "\\[[$path]($style)[$lock_symbol]($lock_style)\\] "
style = "bold red"

[character]
# success_symbol = "[â¯](bold yellow)"
# error_symbol = "[âœ—](bold red)"
# vicmd_symbol = "[â®](bold yellow)"
# success_symbol = "[[>](red)[>](yellow)[>](green)](bold green)"
# error_symbol = "[[>](green)[>](yellow)[>](red)](bold red)"
# vicmd_symbol = "[[>](red)[>](green)[>](yellow)](bold yellow)"
success_symbol = "[â†ª](bold green)"
error_symbol = "[â†ª](bold red)"
vicmd_symbol = "[â†©](bold yellow)"

[cmd_duration]
format = 'in \[[â°$duration]($style)\]'

[git_branch]
format = "[\\($symbol$branch\\)]($style) "
symbol = "îœ¥ "
style = "bold yellow"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”–tag "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"
bisect = "[â™»ï¸ BISECT](bold  green)"
merge = "[ğŸ”€ MERGEING](bold  yellow)"

[git_status]
conflicted = "ğŸš©"
untracked = '[?\($count\)](red)'
modified = '[!\($count\)](yellow)' 
stashed = "ğŸ—ƒï¸"
staged = '[+\($count\)](green)'
deleted = "${count}ğŸ—‘ï¸"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[docker_context]
format = "[ğŸ‹ $context](blue bold)"

[aws]
symbol = "îŒ½  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\] '

[conda]
symbol = "ï„Œ "
format = '\[[$symbol$environment]($style)\] '

[dart]
symbol = "î˜ "
format = '\[[$symbol($version)]($style)\] '

[elixir]
symbol = "î‰µ "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\] '

[elm]
symbol = "î˜¬ "
format = '\[[$symbol($version)]($style)\] '

[golang]
symbol = "î˜§ "
format = '\[[$symbol($version)]($style)\] '

[java]
symbol = "î‰– "
format = '\[[$symbol($version)]($style)\] '

[julia]
symbol = "î˜¤ "
format = '\[[$symbol($version)]($style)\] '

[memory_usage]
symbol = "ï¡š "
format = '\[$symbol[$ram( | $swap)]($style)\] '

[nim]
symbol = "ïš¤ "
format = '\[[$symbol($version)]($style)\] '

[nix_shell]
symbol = "ï‹œ "
format = '\[[$symbol$state( \($name\))]($style)\] '

[package]
symbol = "ï£– "
format = '\[[$symbol$version]($style)\] '

[perl]
symbol = "î© "
format = '\[[$symbol($version)]($style)\] '

[php]
symbol = "î˜ˆ "
format = '\[[$symbol($version)]($style)\] '

[python]
symbol = "î˜† "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '

[ruby]
symbol = "îˆ¾ "
format = '\[[$symbol($version)]($style)\] '

[rust]
symbol = "î¨ "
format = '\[[$symbol($version)]($style)\] '

[scala]
symbol = "îœ· "
format = '\[[$symbol($version)]($style)\] '

[shlvl]
symbol = "ï„  "

[swift]
symbol = "ï¯£ "
format = '\[[$symbol($version)]($style)\] '

[cmake]
format = '\[[$symbol($version)]($style)\] '

[crystal]
format = '\[[$symbol($version)]($style)\] '

[dotnet]
format = '\[[$symbol($version)(ğŸ¯ $tfm)]($style)\] '

[erlang]
format = '\[[$symbol($version)]($style)\] '

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\] '

[helm]
format = '\[[$symbol($version)]($style)\] '

[kotlin]
format = '\[[$symbol($version)]($style)\] '

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\] '

[lua]
format = '\[[$symbol($version)]($style)\] '

[nodejs]
format = '\[[$symbol($version)]($style)\] '

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\] '

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\] '

[purescript]
format = '\[[$symbol($version)]($style)\] '

[red]
format = '\[[$symbol($version)]($style)\] '

[terraform]
format = '\[[$symbol$workspace]($style)\] '

[time]
format = '\[[$time]($style)\] '

[username]
format = '\[[$user]($style)\] '

[vagrant]
format = '\[[$symbol($version)]($style)\] '

[vlang]
format = '\[[$symbol($version)]($style)\] '

[zig]
format = '\[[$symbol($version)]($style)\] '
